version: '3'
services:
  ###Inventory (PostgreSQL)
  db-inventory:
    container_name: db-inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: prueba123
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ###Orders (MYSQL)
  db-orders:
    container_name: db-orders
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: prueba123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306

  ###Products (PostgreSQL)
  db-products:
    container_name: db-products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: prueba123
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  ### Clients (MongoDB)
  db-clients:
    container_name: db-clients
    image: mongo:5.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ms_clients
      MONGO_INITDB_ROOT_USERNAME: ecommerce
      MONGO_INITDB_ROOT_PASSWORD: prueba123
    ports:
      - 27017:27017
    expose:
      - 27017
